// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ReactReduxComponentManagement.Data;
using System;

namespace ReactReduxComponentManagement.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20171230082222_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReactReduxComponentManagement.Models.PageCategory", b =>
                {
                    b.Property<int>("PageCategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Keywords");

                    b.Property<string>("PageHtml");

                    b.Property<int>("ParentId");

                    b.Property<string>("Subtitle");

                    b.Property<string>("Title");

                    b.Property<bool>("isCategory");

                    b.HasKey("PageCategoryId");

                    b.ToTable("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
